title: Fabrizio Salvade
description: Apresentacao, curriculo e artigos.
url: "https://brizzio.github.io"
baseurl: ""
theme: minima

author:
  name: Fabrizio Salvade
  email:

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - curriculum.md
  - blog.md

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/brizzio"

