title: Fabrizio Salvade
description: Apresentacao, curriculum e artigos.
url: "https://brizzio.github.io"
baseurl: ""
lang: pt-BR
locale: pt_BR

author:
  name: Fabrizio Salvade

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
